/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as MatchupsRouteImport } from './routes/matchups'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupsRoute = MatchupsRouteImport.update({
  id: '/matchups',
  path: '/matchups',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRoute
  '/matchups': typeof MatchupsRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRoute
  '/matchups': typeof MatchupsRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/insights': typeof InsightsRoute
  '/matchups': typeof MatchupsRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/insights' | '/matchups' | '/strategy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/insights' | '/matchups' | '/strategy'
  id: '__root__' | '/' | '/about' | '/insights' | '/matchups' | '/strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InsightsRoute: typeof InsightsRoute
  MatchupsRoute: typeof MatchupsRoute
  StrategyRoute: typeof StrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchups': {
      id: '/matchups'
      path: '/matchups'
      fullPath: '/matchups'
      preLoaderRoute: typeof MatchupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InsightsRoute: InsightsRoute,
  MatchupsRoute: MatchupsRoute,
  StrategyRoute: StrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
